Downloads/BaiTap/BaiTap/Controllers/QuanLyTonKhoController.cs
using BaiTap.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Serialization;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;

namespace BaiTap.Controllers
{
    public class QuanLyTonKhoController : Controller
    {
        private Model1 db = new Model1();
        // GET: QuanLyTonKho
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SanPhamTonKho()
        {
            List<TonKho> ds = db.TonKhoes.ToList();
            
              return View(ds);
        }
        public ActionResult Nhap() {
            return View(new PhieuNhapKhoViewModel()); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KiemTra(PhieuNhapKhoViewModel model)
        {
            if (model.SanPhamID.HasValue)
            {
                var sanpham = db.SanPhams.Find(model.SanPhamID.Value);
                if(sanpham != null)
                {
                    return RedirectToAction("nhap1");
                }
            }
            else
            {
                return RedirectToAction("NhapKho");
            }
            return View(model);
        }
        public ActionResult nhap1(int id)
        {
            var sanPham = db.SanPhams.Find(id);
            if (sanPham != null) {
                var viewModel = new PhieuNhapKhoViewModel 
                { 
                    SanPhamID = sanPham.SanPhamID, 
                    soluong = sanPham.Soluong ?? 0,
                    Gia = sanPham.Gia ?? 0 
                };
                return View(viewModel); 
            }
            return HttpNotFound();
        }
        [HttpPost]
        
        public ActionResult nhap1(PhieuNhapKhoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var sp = db.SanPhams.FirstOrDefault(p => p.SanPhamID == model.SanPhamID);
                var sp1 = db.TonKhoes.FirstOrDefault(p => p.SanPhamID == model.SanPhamID);
                if (sp != null)
                {
                    sp.Soluong += model.soluong;
                    sp.Gia = model.Gia;
                    sp1.SoLuongTon += model.soluong;
                    db.SaveChanges();
                    var tonkho = new TonKho()
                    {
                        SanPhamID = sp.SanPhamID,
                        SoLuongTon = model.soluong,
                        NgayCapNhat = DateTime.Now,
                    };
                    db.TonKhoes.Add(tonkho);
                    db.SaveChanges();
                    return RedirectToAction("SanPhamTonKho");
                }
            }
            return View(model);
        }
        public ActionResult NhapKho()
        {
            var viewmodel = new PhieuNhapKhoViewModel
            {
                SanPham = new SanPham(),
                ChiTietSanPham = new ChiTietSanPham(),
                TonKho = new TonKho()
            };
            return View(viewmodel);
            //return View(new PhieuNhapKhoViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NhapKho(PhieuNhapKhoViewModel model)
        {
            if(ModelState.IsValid)
            { 
                    if (!string.IsNullOrEmpty(model.DanhMucMoi))
                    {
                        var danhmuc = db.DanhMucs.FirstOrDefault(dm => dm.TenDanhMuc == model.DanhMucMoi);
                        if (danhmuc == null)
                        {
                            danhmuc = new DanhMuc { TenDanhMuc = model.DanhMucMoi };
                            db.DanhMucs.Add(danhmuc);
                            db.SaveChanges();
                        }
                        model.SanPham.DanhMucID = danhmuc.DanhMucID;
                    }
                    if (!string.IsNullOrEmpty(model.HangsxMoi))
                    {
                        var hang = db.Hangs.FirstOrDefault(h => h.TenHang == model.HangsxMoi);
                        if (hang == null)
                        {
                            hang = new Hang { TenHang = model.HangsxMoi };
                            db.Hangs.Add(hang);
                            db.SaveChanges();
                        }
                    }
                        var sanpham = model.SanPham;
                        db.SanPhams.Add(sanpham);
                        db.SaveChanges();

                         var ChiTiet = model.ChiTietSanPham;
                        model.ChiTietSanPham.SanPhamID = model.SanPham.SanPhamID;
                        db.ChiTietSanPhams.Add(ChiTiet);
                        db.SaveChanges();

                        model.TonKho.SanPhamID = model.SanPham.SanPhamID;
                        model.TonKho.NgayCapNhat = DateTime.Now;
                        db.TonKhoes.Add(model.TonKho);
                        db.SaveChanges();
                        return RedirectToAction("SanPhamTonKho");

            }
            return View(model);
        }
      

        public ActionResult XuatKho()
        {
            return View();
        }
        
        
        public ActionResult Sapxep()
        {
            return View();
        }
    }
}

Downloads/BaiTap/BaiTap/Views/QuanLyTonKho/SanPhamTonKho.cshtml
@model IEnumerable<BaiTap.Models.TonKho>

@{
    ViewBag.Title = "SanPhamTonKho";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SanPhamTonKho</h2>


<main id="main" class="main" style="width:100%">

    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <!-- Left side columns tim de thay doi chieu rong cua giao dien ben phai -->
            <div class="col-lg-8" style="width:1200px">

                <div class="row">

                    <!-- Recent Sales -->
                    <div class="col-12">
                        <div class="card recent-sales overflow-auto">

                            <div class="filter">
                                <a class="icon" href="#" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></a>
                                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                    <li class="dropdown-header text-start">
                                        <h6>Filter</h6>
                                    </li>

                                    <li><a class="dropdown-item" href="#">Today</a></li>
                                    <li><a class="dropdown-item" href="#">This Month</a></li>
                                    <li><a class="dropdown-item" href="#">This Year</a></li>
                                </ul>
                            </div>

                            <div class="card-body">
                                <h5 class="card-title">Recent Sales <span>| Today</span></h5>

                                <table class="table table-borderless datatable" style="font-size: 14px">

                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.SanPhamID)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.SoLuongTon)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.NgayCapNhat)
                                        </th>
                                        <th></th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.SanPhamID)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.SoLuongTon)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NgayCapNhat)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.TonKhoID }) |
                                                @Html.ActionLink("Details", "Details", new { id = item.TonKhoID }) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.TonKhoID })
                                            </td>
                                        </tr>
                                    }


                                </table>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <div class="form-actions no-color">
        <a href="@Url.Action("Nhap", "QuanLyTonKho")" class="btn btn-default">Nhap kho</a>

    </div>
</main><!-- End #main -->
<!-- Button to trigger modal -->

Downloads/BaiTap/BaiTap/Views/QuanLyTonKho/nhap.cshtml
@model BaiTap.Models.PhieuNhapKhoViewModel
<h2>SanPhamTonKho</h2>


<main id="main" class="main" style="width:100%">

    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <!-- Left side columns tim de thay doi chieu rong cua giao dien ben phai -->
            <div class="col-lg-8" style="width:1200px">
                @using (Html.BeginForm("KiemTra", "QuanLyTonKho", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        @Html.LabelFor(m => m.SanPhamID)
                        @Html.TextBoxFor(m => m.SanPhamID, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary">Tiếp tục</button>
                }
            </div>
        </div>

    </section>

</main><!-- End #main -->

Downloads/BaiTap/BaiTap/Views/QuanLyTonKho/nhap1.cshtml
@model BaiTap.Models.PhieuNhapKhoViewModel
<h2>SanPhamTonKho</h2>


<main id="main" class="main" style="width:100%">

    <div class="pagetitle">
        <h1>Dashboard</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <!-- Left side columns tim de thay doi chieu rong cua giao dien ben phai -->
            @using (Html.BeginForm("Nhap1", "QuanLyTonKho", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-group"> @Html.LabelFor(m => m.soluong) 
                    @Html.TextBoxFor(m => m.soluong, new { @class = "form-control" })
                </div> 
                <div class="form-group">
                    @Html.LabelFor(m => m.Gia) @Html.TextBoxFor(m => m.Gia, new { @class = "form-control" })
                 </div> 
                 <button type="submit" class="btn btn-primary">Lưu</button>
            }
        </div>

    </section>

</main><!-- End #main -->